### ISSUE TITLE
roadmap?

### ISSUE THREAD

**Issue by RallyTronics** [DragonJoker/RendererLib#2]
I have been keeping an eye on your project, do you have a roadmap to where you are heading?

**Comment by DragonJoker** [comment]
The roadmap, roughly, is : implement all features provided in Vulkan.
I don't know how much I can achieve from this, but I'll do as far as I can.
A thing to know, is that I've started this project, because I need to upgrade Castor3D, to use Vulkan, and I needed that kind of library, to replace my current renderer (OpenGL).
I needed a way to work with OpenGL like we need to work with Vulkan.

**Comment by RallyTronics** [comment]
Thanks for the info!
